### ISSUE TITLE
Update plugin to use python-lsp-server instead of python-language-server

### ISSUE THREAD

**Issue by andfoy** [QuantStack/pyls-memestra#42]
Hi,

Given that Palantir removed all the community maintenance for both python-language-server (pyls) and python-jsonrpc-server (pyls_jsonrpc), we decided to create a separate organization that now maintains a community-based fork for the aforementioned packages, which can be found at: https://github.com/python-lsp/python-lsp-server and https://github.com/python-lsp/python-lsp-jsonrpc.

Our recommendation is to migrate this plugin to be compatible with the community server instead of the Palantir one. In order to do so, here is a migration guide that should help:

1. The plugin should replace `python-language-server` by `python-lsp-server` on its requirements.
2. The `pyls` namespace is now `pylsp`, which means that all `pyls` imports should be replaced by `pylsp`.
3. The `pyls_*` hookspecs are now `pylsp_*` hookspecs.
4. The plugin can preserve the `pyls_` prefix on its namespace in order to prevent further administration and release issues that may arise from renaming it.

Feel free to ask any question about the migration process or about the new community organization for the server.

**Comment by marimeireles** [comment]
Hey @andfoy, thanks for opening an issue here!
I'm aware of the new org. and will make the  changes for a next release.
Thanks again!

**Comment by marimeireles** [comment]
I'm facing this issue where `pyls-memestra` doesn't work if I try to use `pylsp`. I don't really get why because I get zero errors, either in the jupyterlab terminal or the browser console.

This extension depends on `jupyter-lsp` and I built the current master version in my local env. This version supports `pylsp`.

You can see my changes in the PR https://github.com/QuantStack/pyls-memestra/pull/43/files and here's a screenshot:

![image](https://user-images.githubusercontent.com/17600982/116315642-55bd3000-a7a0-11eb-9467-62d6312b9031.png)

The `some_old_function` was supposed to be underlined, for example, but it isn't.

As you can see other plugins that are dependent on `python-language-server` are still working, and if I reset these changes, `pyls-memestra` works too.

Any leads on what I might be doing wrong will be of great help!

**Comment by andfoy** [comment]
I think you forgot to use `pylsp_*` hookspecs instead of `pyls_*` ones

**Comment by marimeireles** [comment]
True!
Thank you :)

**Comment by marimeireles** [comment]
Closing this issue. A new version will come out as soon as a new version of jupyter-lsp comes out too :)
Thanks @andfoy!
